@echo off
echo Creating output directory...
mkdir -p out
echo Compiling Java files...
javac -d out -cp "./lib/json-simple-1.1.1.jar;./lib/junit-platform-console-standalone-1.9.2.jar" src/*.java
echo Running application...
java -cp "out;./lib/json-simple-1.1.1.jar;./lib/junit-platform-console-standalone-1.9.2.jar" src.CourseUI
pause 